<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <RootNamespace>RemoteManager</RootNamespace>
    <AssemblyName>RemoteManager</AssemblyName>
    <LangVersion>latest</LangVersion>
    <PluginName>RemoteManager</PluginName>
    <StopSmartClient>true</StopSmartClient>
    <LaunchSmartClient>true</LaunchSmartClient>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome5" Version="2.1.11" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
    <PackageReference Include="MilestoneSystems.VideoOS.Platform" Version="*-*" />
    <PackageReference Include="System.Text.Json" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Security" />
    <Reference Include="WindowsFormsIntegration" />
    <Reference Include="AxMSTSCLib">
      <HintPath>lib\AxMSTSCLib.dll</HintPath>
    </Reference>
    <Reference Include="MSTSCLib">
      <HintPath>lib\MSTSCLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CommunitySDK\CommunitySDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="plugin.def">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
